"""
Auto-generated by PySpring CLI (dev update-init)
"""

from pyspring.core.utils.imports.auto import import_package
from pyspring.security.authentication.config.auto_config import (
    AuthenticationConfiguration,
)

__all__ = import_package(__name__, globals())
