"""
Auto-generated by PySpring CLI (dev update-init)
"""
from pyspring.core.ioc.interfaces.core import ILifecycle, IManaged  # noqa: F401  # re-export
from pyspring.core.utils.imports.auto import import_package

__all__ = import_package(__name__, globals())
