"""
Auto-generated by PySpring CLI (dev update-init)
"""
from pyspring.security.authentication.config.auto_config import AuthenticationConfiguration
from pyspring.utils.imports.auto import import_package

# Backward compatibility alias
SecurityAutoConfiguration = AuthenticationConfiguration

__all__ = import_package(__name__, globals())
