"""
Auto-generated by PySpring CLI (dev update-init)
"""
from pyspring.ioc.interfaces.core import IManaged, ILifecycle
from pyspring.utils.imports.auto import import_package

__all__ = import_package(__name__, globals())
