"""
Auto-generated by PySpring CLI (dev update-init)
"""
from pyspring.core.utils.imports.auto import import_package

# 使用动态导入，根据执行上下文决定导入哪些模块
# CLI模式下会排除重型运行时模块，提升CLI性能
__all__ = import_package(__name__, globals(), exclude=['cli'])
