import ast
import os
from typing import List, Tuple, Optional

from pyspring.cli.core.ui import print_success, print_error, print_info


def get_defined_symbols(file_path: str) -> Tuple[List[str], Optional[List[str]]]:
    """
    Parse a Python file and return (defined_symbols, all_list)
    defined_symbols: Classes and Functions defined in this file (public only)
    all_list: Content of __all__ if defined, else None
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        try:
            tree = ast.parse(f.read(), filename=file_path)
        except SyntaxError:
            print_error(f"Syntax error in {file_path}")
            return [], None

    defined = []
    all_exports = None

    for node in tree.body:
        # Check for __all__ assignment
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == '__all__':
                    # Try to evaluate the list
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        all_exports = []
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                all_exports.append(elt.value)
                            elif isinstance(elt, ast.Str):  # Python < 3.8
                                all_exports.append(elt.s)

        # Check for definitions
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if not node.name.startswith('_'):
                defined.append(node.name)

        # Check for variable assignments (e.g. VERSION = "1.0", x: int = 1)
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    if not target.id.startswith('_'):
                        defined.append(target.id)

        if isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name):
                if not node.target.id.startswith('_'):
                    defined.append(node.target.id)

    return defined, all_exports


def get_package_name(pkg_path: str) -> str:
    """
    Guess the full package name from the file system path.
    Assumes structure: .../src/package/subpackage
    """
    abs_path = os.path.abspath(pkg_path)

    # Try finding 'src' in the path
    parts = abs_path.split(os.sep)
    try:
        if 'src' in parts:
            idx = parts.index('src')
            # Join everything after 'src'
            pkgs = parts[idx + 1:]
            return ".".join(pkgs)
        else:
            # Fallback: Assume the directory name is the package name (top level?)
            # This might be incorrect for nested packages outside src structure.
            return os.path.basename(abs_path)
    except Exception:
        return os.path.basename(abs_path)


def generate_dynamic_content() -> str:
    """
    Generate content for dynamic __init__.py
    """
    return '''"""
Auto-generated by PySpring CLI (dev sync-exports)
"""
from utils.auto_import import auto_import_package

__all__ = auto_import_package(__name__, globals())
'''


def generate_init_content(pkg_path: str, modules: dict, use_absolute: bool = False) -> str:
    """
    Generate content for __init__.py
    modules: dict { filename_no_ext: [symbols] }
    """
    lines = [
        '"""',
        'Auto-generated by PySpring CLI (dev sync-exports)',
        '"""'
    ]

    # ... logic for explicit imports ...

    pkg_full_name = get_package_name(pkg_path) if use_absolute else ""

    all_list = []

    for mod_name in sorted(modules.keys()):
        symbols = modules[mod_name]

        # Check if it is a sub-package export (Special marker: symbols == [mod_name])
        is_subpkg = (len(symbols) == 1 and symbols[0] == mod_name)

        if is_subpkg:
            if use_absolute:
                import_stmt = f"from {pkg_full_name} import {mod_name}"
            else:
                import_stmt = f"from . import {mod_name}"
            all_list.append(mod_name)
        else:
            if not symbols:
                continue
            all_list.extend(symbols)
            # Sort symbols for stability
            symbols.sort()

            if use_absolute:
                import_stmt = f"from {pkg_full_name}.{mod_name} import {', '.join(symbols)}"
            else:
                import_stmt = f"from .{mod_name} import {', '.join(symbols)}"

        lines.append(import_stmt)

    lines.append("")
    lines.append("__all__ = [")

    # Sort all list
    all_list.sort()
    for symbol in all_list:
        lines.append(f"    '{symbol}',")
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def sync_exports(args):
    """
    Sync exported symbols in __init__.py for a given package directory.
    """
    target_path = os.path.abspath(args.path)

    if not os.path.isdir(target_path):
        print_error(f"Target path is not a directory: {target_path}")
        return

    print_info(f"Scanning package: {target_path}")

    # Check flags for mode
    use_absolute = getattr(args, 'absolute', True)
    use_relative = getattr(args, 'relative', False)

    # Special Case: --absolute requested to mean "Dynamic Auto Import"
    # The user requested that "--absolute" generates the auto_import_package code.
    # While confusing naming, we stick to the user's mapping.
    # Logic: 
    # If --relative is specified -> Use Explicit Relative
    # If --absolute is specified (default) -> Use Dynamic (Auto Import) code as requested

    if not use_relative:
        # Dynamic Mode (mapped to "Absolute" flag per request)
        content = generate_dynamic_content()
        init_path = os.path.join(target_path, '__init__.py')
        with open(init_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print_success(f"Updated {init_path} (Dynamic Import)")
        return

    # Else: Explicit Relative Mode logic

    # 1. Scan .py files
    files = [f for f in os.listdir(target_path) if f.endswith('.py') and f != '__init__.py']

    # 2. Scan Sub-directories (Packages)
    dirs = [d for d in os.listdir(target_path) if os.path.isdir(os.path.join(target_path, d))
            and os.path.exists(os.path.join(target_path, d, '__init__.py'))
            and not d.startswith('_') and d != '__pycache__']

    items = sorted(files + dirs)

    modules_map = {}

    for item in items:
        full_path = os.path.join(target_path, item)
        is_pkg = os.path.isdir(full_path)

        if is_pkg:
            # Scheme B: Do not flatten sub-packages.
            # Just export the package name itself to allow 'from package import subpackage'
            # and autocompletion support.
            mod_name = item
            modules_map[mod_name] = [item]  # Self-reference logic handled in generator
            print(f"  - {item}: Found sub-package")
            continue

        # If file, parse it
        defined, explicit_all = get_defined_symbols(full_path)

        # Logic: If __all__ exists, use it. Else use defined public symbols.
        if explicit_all is not None:
            symbols = explicit_all
        else:
            symbols = defined

        if symbols:
            mod_name = item[:-3]
            modules_map[mod_name] = symbols
            print(f"  - {item}: Found {len(symbols)} exports")

    if not modules_map:
        print_info("No exports found.")
        return

    # Check flags
    # use_absolute = getattr(args, 'absolute', True) # Legacy logic
    # if getattr(args, 'relative', False):
    #     use_absolute = False

    # Force using relative for explicit generation if we are here
    content = generate_init_content(target_path, modules_map, use_absolute=False)

    init_path = os.path.join(target_path, '__init__.py')

    with open(init_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print_success(f"Updated {init_path} (Explicit Relative Import)")

    print_success(f"Updated {init_path}")
