import ast
import os
from typing import List, Tuple, Optional

from pyspring.cli.core.ui import (
    print_error, print_info, print_title,
    print_issue, print_summary
)


def get_defined_symbols(file_path: str) -> Tuple[List[str], Optional[List[str]]]:
    """
    Parse a Python file and return (defined_symbols, all_list)
    defined_symbols: Classes and Functions defined in this file (public only)
    all_list: Content of __all__ if defined, else None
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        try:
            tree = ast.parse(f.read(), filename=file_path)
        except SyntaxError as e:
            print_issue(str(e.lineno or 0), f"Syntax Error: {e.msg}", file_path, level='error')
            return [], None

    defined = []
    all_exports = None

    for node in tree.body:
        # Check for __all__ assignment
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == '__all__':
                    # Try to evaluate the list
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        all_exports = []
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                all_exports.append(elt.value)
                            elif isinstance(elt, ast.Str):  # Python < 3.8
                                all_exports.append(elt.s)

        # Check for definitions
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if not node.name.startswith('_'):
                defined.append(node.name)

        # Check for variable assignments (e.g. VERSION = "1.0", x: int = 1)
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    if not target.id.startswith('_'):
                        defined.append(target.id)

        if isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name):
                if not node.target.id.startswith('_'):
                    defined.append(node.target.id)

    return defined, all_exports


def get_package_name(pkg_path: str) -> str:
    """
    Guess the full package name from the file system path.
    Assumes structure: .../src/package/subpackage
    """
    abs_path = os.path.abspath(pkg_path)

    # Try finding 'src' in the path
    parts = abs_path.split(os.sep)
    try:
        if 'src' in parts:
            idx = parts.index('src')
            # Join everything after 'src'
            pkgs = parts[idx + 1:]
            return ".".join(pkgs)
        else:
            # Fallback
            return os.path.basename(abs_path)
    except Exception:
        return os.path.basename(abs_path)


def generate_dynamic_content() -> str:
    """
    Generate content for dynamic __init__.py
    """
    return '''"""
Auto-generated by PySpring CLI (dev sync-exports)
"""
from utils.auto_import import auto_import_package

__all__ = auto_import_package(__name__, globals())
'''


def generate_init_content(pkg_path: str, modules: dict, use_absolute: bool = False) -> str:
    """
    Generate content for __init__.py
    modules: dict { filename_no_ext: [symbols] }
    """
    lines = [
        '"""',
        'Auto-generated by PySpring CLI (dev sync-exports)',
        '"""'
    ]

    # ... logic for explicit imports ...

    pkg_full_name = get_package_name(pkg_path) if use_absolute else ""

    all_list = []

    for mod_name in sorted(modules.keys()):
        symbols = modules[mod_name]

        # Check if it is a sub-package export (Special marker: symbols == [mod_name])
        is_subpkg = (len(symbols) == 1 and symbols[0] == mod_name)

        if is_subpkg:
            if use_absolute:
                import_stmt = f"from {pkg_full_name} import {mod_name}"
            else:
                import_stmt = f"from . import {mod_name}"
            all_list.append(mod_name)
        else:
            if not symbols:
                continue
            all_list.extend(symbols)
            # Sort symbols for stability
            symbols.sort()

            if use_absolute:
                import_stmt = f"from {pkg_full_name}.{mod_name} import {', '.join(symbols)}"
            else:
                import_stmt = f"from .{mod_name} import {', '.join(symbols)}"

        lines.append(import_stmt)

    lines.append("")
    lines.append("__all__ = [")

    # Sort all list
    all_list.sort()
    for symbol in all_list:
        lines.append(f"    '{symbol}',")
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def process_fixed_recursive(target_path: str) -> int:
    """
    Recursively process directory for fixed exports.
    Returns count of updated files.
    """
    updated_count = 0
    # 1. Scan .py files
    try:
        files = [f for f in os.listdir(target_path) if f.endswith('.py') and f != '__init__.py']
    except FileNotFoundError:
        return 0

    # 2. Scan Sub-directories (Packages)
    dirs = [d for d in os.listdir(target_path) if os.path.isdir(os.path.join(target_path, d))
            and os.path.exists(os.path.join(target_path, d, '__init__.py'))
            and not d.startswith('_') and d != '__pycache__']

    # Recurse first
    for d in dirs:
        updated_count += process_fixed_recursive(os.path.join(target_path, d))

    # Process current dir
    items = sorted(files + dirs)
    modules_map = {}

    for item in items:
        full_path = os.path.join(target_path, item)
        is_pkg = os.path.isdir(full_path)

        if is_pkg:
            # Scheme B: Export sub-package name
            mod_name = item
            modules_map[mod_name] = [item]
            continue

        # If file, parse it
        defined, explicit_all = get_defined_symbols(full_path)

        if explicit_all is not None:
            symbols = explicit_all
        else:
            symbols = defined

        if symbols:
            mod_name = item[:-3]
            modules_map[mod_name] = symbols

    if not modules_map:
        return updated_count

    content = generate_init_content(target_path, modules_map, use_absolute=False)
    init_path = os.path.join(target_path, '__init__.py')

    with open(init_path, 'w', encoding='utf-8') as f:
        f.write(content)

    # print_file_header(init_path) # Too verbose if recursive? 
    # Let's just print a success issue
    print_issue("1", "Updated Explicit Exports", init_path, level='success')
    return updated_count + 1


def sync_exports(args):
    """
    Sync exported symbols in __init__.py for a given package directory.
    """
    target_path = os.path.abspath(args.path)

    if not os.path.isdir(target_path):
        print_error(f"Target path is not a directory: {target_path}")
        return

    is_fixed = getattr(args, 'fixed', False)

    print_title(f"Sync Exports: {target_path}")

    if is_fixed:
        print_info("Mode: Recursive Fixed")
        count = process_fixed_recursive(target_path)
        print_summary(0, 0, count, fixable=False)
    else:
        # Dynamic Mode (Default)
        print_info("Mode: Dynamic")
        content = generate_dynamic_content()
        init_path = os.path.join(target_path, '__init__.py')
        with open(init_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print_issue("1", "Updated Dynamic Import", init_path, level='success')
        print_summary(0, 0, 1, fixable=False)
